# Generated by Django 4.1 on 2023-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_token_transaction_history_alter_type_transac_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='description2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='token2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='type_actif2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
