# Generated by Django 4.1 on 2023-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_history_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='unit_price1',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='value1',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
