# Generated by Django 4.1 on 2023-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_history_unit_price1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='unit_price2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='value2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
