# Generated by Django 4.1 on 2023-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portefeuille',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
