# Generated by Django 4.1 on 2023-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0003_remove_portefeuille_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='last_update',
            field=models.DateField(default='2023-08-04'),
            preserve_default=False,
        ),
    ]
