API_COINMARKET='6605bbe1-9a78-423c-964a-b0587763da34'
API_VANTAGE='423OIP767ARSVKNP'

AWS_ACCESS_KEY_ID = "AKIARGIJGSFVVLCL6J26"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-2"

ACCES_KEY_DEBANK = "911a2a418fd24f4e0c221c9d3d1baacbeddc2f73"

[passwords]
theocostes = "PXi!p9RpYtxfggi4"