# Generated by Django 4.1 on 2023-08-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateField()),
                ('token', models.CharField(max_length=20)),
                ('amount', models.FloatField(null=True)),
                ('type_actif', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('value', models.FloatField(null=True)),
                ('unit_price', models.FloatField(null=True)),
            ],
        ),
    ]
