name: Collect Quotes Data

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Python script
      env:
        API_COINMARKET: ${ { secrets.API_COINMARKET } }
        API_ALPHA_VANTAGE: ${ { secrets.API_ALPHA_VANTAGE } }
        AWS_ACCESS_KEY_ID: ${ { secrets.AWS_ACCESS_KEY_ID } }
        AWS_SECRET_ACCESS_KEY: ${ { secrets.AWS_SECRET_ACCESS_KEY } }
        AWS_DEFAULT_REGION: ${ { secrets.AWS_DEFAULT_REGION } }
      run: python code_api_aws/collect_data.py


